//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnessify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prehrana
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> id_koris { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public int cal { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
